<?php
/**
 * autogenerated File -- please do not change manually
 */

if (! extension_loaded('xhp')) {
   exit("Please enable xhp extension");
}

echo '<'."?php".PHP_EOL;
echo "if (extension_loaded('xhp')) return;".PHP_EOL;
echo "if (! defined('T_CHARACTER') )";
echo "	define('T_CHARACTER', ".T_CHARACTER.");" . PHP_EOL;
echo "if (! defined('T_BAD_CHARACTER') )";
echo "	define('T_BAD_CHARACTER', ".T_BAD_CHARACTER.");" . PHP_EOL;
echo "if (! defined('T_BACKTICKS_EXPR') )";
echo "	define('T_BACKTICKS_EXPR', ".T_BACKTICKS_EXPR.");" . PHP_EOL;
echo "if (! defined('T_OPEN_TAG_FAKE') )";
echo "	define('T_OPEN_TAG_FAKE', ".T_OPEN_TAG_FAKE.");" . PHP_EOL;
echo "if (! defined('T_HEREDOC') )";
echo "	define('T_HEREDOC', ".T_HEREDOC.");" . PHP_EOL;
echo "if (! defined('T_VARIADIC_PARAMETER') )";
echo "	define('T_VARIADIC_PARAMETER', ".T_VARIADIC_PARAMETER.");" . PHP_EOL;
echo "if (! defined('T_XHP_WHITESPACE') )";
echo "	define('T_XHP_WHITESPACE', ".T_XHP_WHITESPACE.");" . PHP_EOL;
echo "if (! defined('T_XHP_TEXT') )";
echo "	define('T_XHP_TEXT', ".T_XHP_TEXT.");" . PHP_EOL;
echo "if (! defined('T_XHP_ATTRIBUTE') )";
echo "	define('T_XHP_ATTRIBUTE', ".T_XHP_ATTRIBUTE.");" . PHP_EOL;
echo "if (! defined('T_XHP_CATEGORY') )";
echo "	define('T_XHP_CATEGORY', ".T_XHP_CATEGORY.");" . PHP_EOL;
echo "if (! defined('T_XHP_CATEGORY_LABEL') )";
echo "	define('T_XHP_CATEGORY_LABEL', ".T_XHP_CATEGORY_LABEL.");" . PHP_EOL;
echo "if (! defined('T_XHP_CHILDREN') )";
echo "	define('T_XHP_CHILDREN', ".T_XHP_CHILDREN.");" . PHP_EOL;
echo "if (! defined('T_XHP_ANY') )";
echo "	define('T_XHP_ANY', ".T_XHP_ANY.");" . PHP_EOL;
echo "if (! defined('T_XHP_PCDATA') )";
echo "	define('T_XHP_PCDATA', ".T_XHP_PCDATA.");" . PHP_EOL;
echo "if (! defined('T_XHP_COLON') )";
echo "	define('T_XHP_COLON', ".T_XHP_COLON.");" . PHP_EOL;
echo "if (! defined('T_XHP_HYPHEN') )";
echo "	define('T_XHP_HYPHEN', ".T_XHP_HYPHEN.");" . PHP_EOL;
echo "if (! defined('T_XHP_BOOLEAN') )";
echo "	define('T_XHP_BOOLEAN', ".T_XHP_BOOLEAN.");" . PHP_EOL;
echo "if (! defined('T_XHP_NUMBER') )";
echo "	define('T_XHP_NUMBER', ".T_XHP_NUMBER.");" . PHP_EOL;
echo "if (! defined('T_XHP_MIXED') )";
echo "	define('T_XHP_MIXED', ".T_XHP_MIXED.");" . PHP_EOL;
echo "if (! defined('T_XHP_STRING') )";
echo "	define('T_XHP_STRING', ".T_XHP_STRING.");" . PHP_EOL;
echo "if (! defined('T_XHP_ENUM') )";
echo "	define('T_XHP_ENUM', ".T_XHP_ENUM.");" . PHP_EOL;
echo "if (! defined('T_XHP_FLOAT') )";
echo "	define('T_XHP_FLOAT', ".T_XHP_FLOAT.");" . PHP_EOL;
echo "if (! defined('T_XHP_CALLABLE') )";
echo "	define('T_XHP_CALLABLE', ".T_XHP_CALLABLE.");" . PHP_EOL;
echo "if (! defined('T_XHP_REQUIRED') )";
echo "	define('T_XHP_REQUIRED', ".T_XHP_REQUIRED.");" . PHP_EOL;
echo "if (! defined('T_XHP_LABEL') )";
echo "	define('T_XHP_LABEL', ".T_XHP_LABEL.");" . PHP_EOL;
echo "if (! defined('T_XHP_TAG_LT') )";
echo "	define('T_XHP_TAG_LT', ".T_XHP_TAG_LT.");" . PHP_EOL;
echo "if (! defined('T_XHP_TAG_GT') )";
echo "	define('T_XHP_TAG_GT', ".T_XHP_TAG_GT.");" . PHP_EOL;
echo "if (! defined('T_TYPELIST_LT') )";
echo "	define('T_TYPELIST_LT', ".T_TYPELIST_LT.");" . PHP_EOL;
echo "if (! defined('T_TYPELIST_GT') )";
echo "	define('T_TYPELIST_GT', ".T_TYPELIST_GT.");" . PHP_EOL;
echo "if (! defined('T_UNRESOLVED_OP') )";
echo "	define('T_UNRESOLVED_OP', ".T_UNRESOLVED_OP.");" . PHP_EOL;
echo "if (! defined('T_UNRESOLVED_LT') )";
echo "	define('T_UNRESOLVED_LT', ".T_UNRESOLVED_LT.");" . PHP_EOL;
echo "if (! defined('T_UNICODE_CAST') )";
echo "	define('T_UNICODE_CAST', ".T_UNICODE_CAST.");" . PHP_EOL;
echo "if (! defined('T_BINARY_CAST') )";
echo "	define('T_BINARY_CAST', ".T_BINARY_CAST.");" . PHP_EOL;
echo "if (! defined('T_NOELSE') )";
echo "	define('T_NOELSE', ".T_NOELSE.");" . PHP_EOL;
